---
provisioner:
  name: salt_solo
  formula: metrics
  vendor_path: "vendor/_root" 
  state_top:
    base:
      '*':
        - metrics.server
        - metrics.client
  pillars:
    top.sls:
      base:
        '*':
          - testpillar
    testpillar.sls:
      collectd:
        carbon: localhost
  omnibus_cachier: true

platforms:
  - name: vagrant-ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      pre_create_command: "salt-shaker shake root_formula=ministryofjustice/metrics-formula"
      vagrantfile_erb: "kitchenvagrant/Vagrantfile.erb"
      cachier:
        scope: "box"
      customize:
        memory: 1024
      box: "hashicorp/precise64"
      box_url: "https://vagrantcloud.com/hashicorp/boxes/precise64"

  - name: aws-ubuntu-12.04
    driver_plugin: ec2
    driver_config:
      aws_access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY', 'NONE') %>
      aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_KEY', 'NONE') %>
      aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'NONE') %>
      ssh_key: <%= File.expand_path("~/.ssh/#{ENV.fetch('AWS_SSH_KEY_ID', 'NONE')}.pem") %>
      image_id: ami-8e987ef9
      username: ubuntu
      security_group_ids: ["sg-e932d286"]
      region: eu-west-1
      availability_zone: eu-west-1a

suites:
  - name: default
